# .github/workflows/daily_stock_news_modeling.yml
name: Daily Stock News Modeling

on:
  schedule:
    - cron: '0 13 * * *'    # 13:00 UTC = 06:00 PDT
  workflow_dispatch: {}

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export API Key to environment
        run: echo "NEWSDATA_API_KEY=${{ secrets.NEWSDATA_API_KEY }}" >> $GITHUB_ENV

      - name: Download NLTK & TextBlob corpora
        run: |
          python -m nltk.downloader punkt vader_lexicon averaged_perceptron_tagger wordnet
          python -m textblob.download_corpora

      - name: Execute Master Notebook (force full rerun)
        run: |
          # ensure output folder exists
          mkdir -p notebooks

          # clear old outputs and re-execute all cells
          jupyter nbconvert \
            --to notebook \
            --execute notebooks/Master_Data_Modeling.ipynb \
            --ExecutePreprocessor.kernel_name=python3 \
            --ExecutePreprocessor.timeout=-1 \
            --ClearOutputPreprocessor.enabled=True \
            --output-dir notebooks \
            --output Master_Data_Modeling_output.ipynb

      - name: Debug — show scraped date
        run: |
          grep -R "Scraping news for date" notebooks/Master_Data_Modeling_output.ipynb \
            || echo "❌ scrape debug line not found!"

      - name: Show workspace files
        run: ls -R .

      - name: Commit & push outputs
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add notebooks/Master_Data_Modeling_output.ipynb notebooks/*.csv *.xlsx *.txt
          git commit -m "chore: update output notebook and data" || echo "No changes to commit"
          git push
